poetry run python -m cardioner.main --inference_only --model_path=/home/bramiozo/DEV/CardioNER.nl/output/EuroBERT-610m/DISEASE_3l_multilabel_weighted/fold_0 --corpus_inference=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/MultiClinNER-ro/test/disease/txt --lang=multi --output_file_prefix=ro_disease_eurobert610_ml_ --inference_pipe=dt4h --inference_batch_size=4 --trust_remote_code --inference_filter_file=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/batch_1_ids.txt;

poetry run python -m cardioner.main --inference_only --model_path=/home/bramiozo/DEV/CardioNER.nl/output/EuroBERT-610m/DISEASE_3l_multilabel_weighted/fold_0 --corpus_inference=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/MultiClinNER-it/test/disease/txt --lang=multi --output_file_prefix=it_disease_eurobert610_ml_ --inference_pipe=dt4h --inference_batch_size=4 --trust_remote_code --inference_filter_file=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/batch_1_ids.txt;

poetry run python -m cardioner.main --inference_only --model_path=/home/bramiozo/DEV/CardioNER.nl/output/EuroBERT-610m/DISEASE_3l_multilabel_weighted/fold_0 --corpus_inference=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/MultiClinNER-en/test/disease/txt --lang=multi --output_file_prefix=en_disease_eurobert610_ml_ --inference_pipe=dt4h --inference_batch_size=4 --trust_remote_code --inference_filter_file=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/batch_1_ids.txt;

poetry run python -m cardioner.main --inference_only --model_path=/home/bramiozo/DEV/CardioNER.nl/output/EuroBERT-610m/DISEASE_3l_multilabel_weighted/fold_0 --corpus_inference=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/MultiClinNER-es/test/disease/txt --lang=multi --output_file_prefix=es_disease_eurobert610_ml_ --inference_pipe=dt4h --inference_batch_size=4 --trust_remote_code --inference_filter_file=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/batch_1_ids.txt;

poetry run python -m cardioner.main --inference_only --model_path=/home/bramiozo/DEV/CardioNER.nl/output/EuroBERT-610m/DISEASE_3l_multilabel_weighted/fold_0 --corpus_inference=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/MultiClinNER-nl/test/disease/txt --lang=multi --output_file_prefix=nl_disease_eurobert610_ml_ --inference_pipe=dt4h --inference_batch_size=4 --trust_remote_code --inference_filter_file=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/batch_1_ids.txt;

poetry run python -m cardioner.main --inference_only --model_path=/home/bramiozo/DEV/CardioNER.nl/output/EuroBERT-610m/DISEASE_3l_multilabel_weighted/fold_0 --corpus_inference=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/MultiClinNER-cz/test/disease/txt --lang=multi --output_file_prefix=cz_disease_eurobert610_ml_ --inference_pipe=dt4h --inference_batch_size=4 --trust_remote_code --inference_filter_file=/home/bramiozo/DEV/CardioNER.nl/assets/MultiClinNER/batch_1_ids.txt;
